"""Model training and evaluation subpackage (Phase 3).

Provides the three-model experiment pipeline:
- Model A: Logistic Regression (baseline features)
- Model B: XGBoost (baseline features)
- Model C: XGBoost (baseline + graph features)

Plus ablation, explainability, error analysis, and evaluation utilities.
"""

from __future__ import annotations

from src.models.ablation import (
    ABLATION_EXPERIMENTS,
    AblationConfig,
    AblationResult,
    FEATURE_GROUPS,
    get_experiment_feature_columns,
    get_feature_indices,
)
from src.models.baseline import build_logistic_model, fit_logistic, predict_proba
from src.models.error_analysis import (
    FPAnalysis,
    FNAnalysis,
    collect_fp_analysis,
    collect_fn_analysis,
    fn_recall_by_ring_type,
    fp_rate_by_legit_group,
    summarize_fns_by_ring_type,
    summarize_fps_by_group,
)
from src.models.evaluation import (
    CostAnalysis,
    CostConfig,
    MetricBundle,
    RingEvalResult,
    bootstrap_metric_bundle_ci,
    compute_cost,
    compute_metrics,
    evaluate_hidden_scenarios,
    evaluate_rings,
    find_cost_optimal_threshold,
    ring_detection_summary,
    threshold_cost_curve,
)
from src.models.explainability import (
    FeatureImportanceReport,
    compute_shap_values,
    get_xgb_importance,
    shap_dependence_data,
    shap_summary,
)
from src.models.preprocessing import (
    FORBIDDEN_FEATURES,
    SUSPICIOUS_TOKENS,
    audit_features,
    get_feature_lists,
    get_feature_matrix,
    load_feature_split,
    load_split_data,
    verify_split_identities,
)
from src.models.thresholds import (
    ThresholdResult,
    ThresholdStrategy,
    apply_threshold,
    evaluate_threshold,
    select_threshold,
    select_threshold_balanced,
    select_threshold_high_recall,
    select_threshold_low_fp_rate,
    select_threshold_max_f1,
)
from src.models.xgboost_model import (
    build_xgboost_model,
    fit_xgboost,
    get_feature_importance,
    get_feature_importance_weight,
    predict_proba_xgb,
)

__all__ = [
    "ABLATION_EXPERIMENTS",
    "AblationConfig",
    "AblationResult",
    "CostAnalysis",
    "CostConfig",
    "FPAnalysis",
    "FNAnalysis",
    "FeatureImportanceReport",
    "FORBIDDEN_FEATURES",
    "FEATURE_GROUPS",
    "FORBIDDEN_FEATURES",
    "MetricBundle",
    "CostConfig",
    "RingEvalResult",
    "SUSPICIOUS_TOKENS",
    "ThresholdResult",
    "ThresholdStrategy",
    "build_logistic_model",
    "build_xgboost_model",
    "collect_fp_analysis",
    "collect_fn_analysis",
    "compute_cost",
    "compute_metrics",
    "compute_shap_values",
    "evaluate_hidden_scenarios",
    "evaluate_rings",
    "fit_logistic",
    "fit_xgboost",
    "get_experiment_feature_columns",
    "get_feature_importance",
    "get_feature_importance_weight",
    "get_feature_indices",
    "get_feature_lists",
    "get_feature_matrix",
    "get_xgb_importance",
    "load_feature_split",
    "load_split_data",
    "predict_proba",
    "predict_proba_xgb",
    "select_threshold",
    "select_threshold_max_f1",
    "select_threshold_balanced",
    "select_threshold_high_recall",
    "select_threshold_low_fp_rate",
    "shap_summary",
    "shap_dependence_data",
    "get_xgb_importance",
    "get_feature_importance",
    "get_feature_importance_weight",
    "get_experiment_feature_columns",
    "get_feature_indices",
    "shap_summary",
    "shap_dependence_data",
    "bootstrap_metric_bundle_ci",
    "CostAnalysis",
    "CostConfig",
    "ThresholdResult",
    "ThresholdStrategy",
    "apply_threshold",
    "evaluate_threshold",
    "select_threshold",
    "select_threshold_balanced",
    "select_threshold_high_recall",
    "select_threshold_low_fp_rate",
    "evaluate_threshold",
    "bootstrap_metric_bundle_ci",
    "compute_cost",
    "compute_metrics",
    "find_cost_optimal_threshold",
    "threshold_cost_curve",
    "ring_detection_summary",
    "evaluate_hidden_scenarios",
    "evaluate_rings",
    "find_cost_optimal_threshold",
    "RingEvalResult",
    "FPAnalysis",
    "FNAnalysis",
    "collect_fp_analysis",
    "collect_fn_analysis",
    "summarize_fps_by_group",
    "summarize_fns_by_ring_type",
    "fn_recall_by_ring_type",
    "fp_rate_by_legit_group",
    "verify_split_identities",
    "audit_features",
    "load_feature_split",
    "load_split_data",
    "FORBIDDEN_FEATURES",
    "SUSPICIOUS_TOKENS",
    "build_logistic_model",
    "build_xgboost_model",
    "fit_logistic",
    "fit_xgboost",
    "predict_proba",
    "predict_proba_xgb",
    "get_feature_importance",
    "get_feature_importance_weight",
    "get_xgb_importance",
    "get_experiment_feature_columns",
    "get_feature_indices",
    "get_feature_lists",
    "get_feature_matrix",
    "shap_summary",
    "shap_dependence_data",
    "compute_shap_values",
    "FeatureImportanceReport",
    "FORBIDDEN_FEATURES",
    "SUSPICIOUS_TOKENS",
]